name: CI — Playwright bypass test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install apt deps required by Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1 \
            libasound2 libpangocairo-1.0-0 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxss1

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          # Use python module to avoid reliance on nodejs/npx
          python -m playwright install --with-deps

      - name: Run bypass test
        env:
          SAMPLE_URL: ${{ secrets.SAMPLE_URL }}
        run: |
          python test_bypass.py